branch-defaults:
  master:
    environment: SampleAutodeploy-env
environment-defaults:
  SampleAutodeploy-env:
    branch: null
    repository: null
global:
  application_name: sample-autodeploy
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:ap-northeast-2::platform/Python 3.6 running
    on 64bit Amazon Linux/2.6.4
  default_region: ap-northeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
